### ISSUE TITLE
I am new to running javascript through github

### ISSUE THREAD

**Issue by piyuveng1** [AABoyles/HIVTrace.js#5]
This is not creating a json file. As you said i did not add any dependencies i used git clone and then used this command  within the HIVTRACE.js folder
node hivtrace -i ./INPUT.FASTA -a resolve -r HXB2_prrt -t .015 -m 500 -g .05 -c
it just goes on the next line without giving me an error. Also do we have to add the hivtrace.js script or the entire folder on the path to bashprofile. Kindly let me know if i am doing this correctly.

**Comment by AABoyles** [comment]
Hi @piyuveng1! Sorry, as you can tell, I haven't been paying attention to this repo. As you discovered, it doesn't actually work yet. If you want to use the HIVTrace workflow, then may I recommend trying either the original [HIVTRACE](https://github.com/veg/hivtrace) or [MicrobeTrace](https://microbetrace.herokuapp.com)?
